from __future__ import annotations

"""Lifecycle and regeneration groundwork.

Defines contracts for safely regenerating existing targets, migration-aware
updates, capability evolution tracking, and long-term maintenance semantics.
"""

import hashlib
import json
from pathlib import Path


# ---------------------------------------------------------------------------
# Regeneration safety policy
# ---------------------------------------------------------------------------

REGEN_SAFETY_LEVELS: dict[str, dict[str, object]] = {
    "safe_overwrite": {
        "level": "safe_overwrite",
        "description": "Generated scaffold files may be overwritten without manual review.",
        "requires_checkpoint": False,
        "requires_approval": False,
        "applicable_to": ["scaffold_only_files", "generated_configs", "autogenerated_routes"],
    },
    "merge_required": {
        "level": "merge_required",
        "description": "File has likely been modified by operator; merge is required before overwrite.",
        "requires_checkpoint": True,
        "requires_approval": False,
        "applicable_to": ["customized_components", "operator_modified_files"],
    },
    "approval_required": {
        "level": "approval_required",
        "description": "Destructive regeneration of production-critical files requires explicit approval.",
        "requires_checkpoint": True,
        "requires_approval": True,
        "applicable_to": ["auth_config", "billing_config", "database_schema_migrations"],
    },
}


def classify_file_regen_safety(
    file_path: str,
    is_autogenerated: bool,
    has_operator_modifications: bool,
    is_production_critical: bool,
) -> dict[str, object]:
    """Classify the regeneration safety level for a given file."""
    if is_production_critical:
        level = REGEN_SAFETY_LEVELS["approval_required"]
    elif has_operator_modifications:
        level = REGEN_SAFETY_LEVELS["merge_required"]
    else:
        level = REGEN_SAFETY_LEVELS["safe_overwrite"]

    return {
        "file_path": file_path,
        "regen_safety_level": level["level"],
        "requires_checkpoint": level["requires_checkpoint"],
        "requires_approval": level["requires_approval"],
        "is_autogenerated": is_autogenerated,
        "has_operator_modifications": has_operator_modifications,
        "is_production_critical": is_production_critical,
    }


# ---------------------------------------------------------------------------
# Migration-aware update contract
# ---------------------------------------------------------------------------

def build_migration_contract(
    from_version: str,
    to_version: str,
    lane_id: str,
    changed_capabilities: list[str] | None = None,
) -> dict[str, object]:
    """Build a migration contract for a version transition."""
    caps = changed_capabilities or []
    requires_data_migration = any(c in caps for c in ["database_schema", "auth_model", "entitlement_model"])
    requires_api_migration = any(c in caps for c in ["api_routes", "api_contracts", "webhook_schema"])

    return {
        "migration_contract_version": "v1",
        "lane_id": lane_id,
        "from_version": from_version,
        "to_version": to_version,
        "changed_capabilities": caps,
        "requires_data_migration": requires_data_migration,
        "requires_api_migration": requires_api_migration,
        "pre_migration_checkpoint_required": requires_data_migration or requires_api_migration,
        "rollback_available": True,
        "migration_steps_scaffold": [
            "run_pre_migration_checks",
            "create_checkpoint_snapshot",
            "apply_schema_migrations" if requires_data_migration else "skip_schema_migrations",
            "apply_api_contract_updates" if requires_api_migration else "skip_api_contract_updates",
            "validate_post_migration_health",
            "record_migration_outcome",
        ],
        "known_limitations": [
            "data migration scripts must be authored and verified by operator",
            "rollback restores code scaffold only; database rollback is operator responsibility",
        ],
    }


# ---------------------------------------------------------------------------
# Capability evolution tracker
# ---------------------------------------------------------------------------

def build_capability_evolution_record(
    lane_id: str,
    capability_family: str,
    previous_maturity: str,
    current_maturity: str,
    promoted_capabilities: list[str] | None = None,
    demoted_capabilities: list[str] | None = None,
) -> dict[str, object]:
    """Record a capability maturity evolution event."""
    promoted = promoted_capabilities or []
    demoted = demoted_capabilities or []
    payload = {
        "record_type": "capability_evolution",
        "lane_id": lane_id,
        "capability_family": capability_family,
        "previous_maturity": previous_maturity,
        "current_maturity": current_maturity,
        "promoted_capabilities": promoted,
        "demoted_capabilities": demoted,
        "net_direction": (
            "promoted" if current_maturity != previous_maturity and not demoted
            else "demoted" if demoted and not promoted
            else "mixed" if promoted and demoted
            else "unchanged"
        ),
    }
    sig = hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    payload["evolution_signature_sha256"] = sig
    return payload


# ---------------------------------------------------------------------------
# Maintenance semantics contract
# ---------------------------------------------------------------------------

MAINTENANCE_SEMANTICS: dict[str, object] = {
    "long_term_maintenance_contract": "v1",
    "scaffold_ownership": "autobuilder_generated",
    "operator_customization_policy": "operator_owned_after_generation",
    "update_strategy": "regenerate_with_merge_review",
    "breaking_change_policy": "require_explicit_migration_contract",
    "deprecation_notice_required": True,
    "lts_lane_designation_required": False,
    "supported_lifecycle_operations": [
        "initial_generation",
        "capability_addition",
        "capability_removal",
        "schema_migration",
        "stack_upgrade",
        "lane_transition",
    ],
    "blocked_lifecycle_operations": [
        "silent_destructive_overwrite",
        "lane_downgrade_without_contract",
    ],
}


def build_lifecycle_contract(lane_id: str) -> dict[str, object]:
    """Build a full lifecycle contract for a lane, including regen + maintenance semantics."""
    return {
        "lane_id": lane_id,
        "lifecycle_contract_version": "v1",
        "maintenance_semantics": MAINTENANCE_SEMANTICS,
        "regen_safety_levels": REGEN_SAFETY_LEVELS,
        "supported_lifecycle_operations": MAINTENANCE_SEMANTICS["supported_lifecycle_operations"],
        "blocked_lifecycle_operations": MAINTENANCE_SEMANTICS["blocked_lifecycle_operations"],
        "migration_contract_available": True,
        "capability_evolution_tracking": True,
        "maturity": "bounded_prototype",
        "known_limitations": [
            "lifecycle tooling is scaffold-contract only; execution requires operator CI integration",
            "migration scripts are not auto-generated from schema diffs",
        ],
    }
