from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path

from generator.plan import BuildOperation, BuildPlan
from platform_hardening.lifecycle import classify_file_regen_safety


@dataclass(frozen=True)
class BuildExecutionResult:
    target_repo: str
    operations_applied: list[dict[str, str]]
    output_hash: str
    output_files: list[dict[str, str]]
    lifecycle_regeneration_decisions: list[dict[str, object]] = field(default_factory=list)

    def to_dict(self) -> dict[str, object]:
        return {
            "target_repo": self.target_repo,
            "operations_applied": self.operations_applied,
            "output_hash": self.output_hash,
            "output_files": self.output_files,
            "lifecycle_regeneration_decisions": self.lifecycle_regeneration_decisions,
        }


def _resolve_scoped_path(target: Path, relative_path: str) -> Path:
    candidate = (target / relative_path).resolve()
    if not str(candidate).startswith(str(target)):
        raise ValueError(f"Operation path escapes target repo: {relative_path}")
    return candidate


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _build_output_manifest(applied: list[dict[str, str]]) -> tuple[list[dict[str, str]], str]:
    output_files = sorted(
        [
            {"path": item["path"], "sha256": item["sha256"]}
            for item in applied
            if item["op"] in {"write_file", "update_file"}
        ],
        key=lambda item: item["path"],
    )
    digest = hashlib.sha256()
    for item in output_files:
        digest.update(item["path"].encode("utf-8"))
        digest.update(b"\n")
        digest.update(item["sha256"].encode("utf-8"))
        digest.update(b"\n")
    return output_files, digest.hexdigest()


def _is_production_critical_path(relative_path: str) -> bool:
    normalized = relative_path.lower()
    return any(
        marker in normalized
        for marker in [
            "db/schema",
            "migration",
            "security/",
            "billing",
            "auth",
            "config",
        ]
    )


def _is_system_managed_metadata_path(relative_path: str) -> bool:
    normalized = relative_path.replace("\\", "/")
    return normalized.startswith(".autobuilder/")


def _apply_operation(
    target: Path,
    op: BuildOperation,
    lifecycle_decisions: list[dict[str, object]],
) -> dict[str, str]:
    resolved = _resolve_scoped_path(target, op.path)

    if op.op == "create_dir":
        resolved.mkdir(parents=True, exist_ok=True)
        return {"op": op.op, "path": op.path, "status": "ok", "sha256": ""}

    if op.op == "write_file":
        if op.content is None:
            raise ValueError(f"write_file operation requires content: {op.path}")
        prior_exists = resolved.exists()
        prior_content = resolved.read_text(encoding="utf-8") if prior_exists else ""
        system_managed = _is_system_managed_metadata_path(op.path)
        decision = classify_file_regen_safety(
            file_path=op.path,
            is_autogenerated=True,
            has_operator_modifications=(prior_exists and prior_content != op.content and not system_managed),
            is_production_critical=_is_production_critical_path(op.path),
        )
        lifecycle_decisions.append(decision)
        if prior_exists and bool(decision.get("requires_approval", False)):
            raise RuntimeError(
                f"Lifecycle guardrail blocked overwrite for '{op.path}': explicit approval required"
            )
        resolved.parent.mkdir(parents=True, exist_ok=True)
        resolved.write_text(op.content, encoding="utf-8")
        expected_hash = _sha256(op.content)
        actual_hash = _sha256_bytes(resolved.read_bytes())
        if expected_hash != actual_hash:
            raise RuntimeError(f"Hash verification failed for generated file: {op.path}")
        return {"op": op.op, "path": op.path, "status": "ok", "sha256": actual_hash}

    if op.op == "update_file":
        if op.content is None:
            raise ValueError(f"update_file operation requires content: {op.path}")
        prior_exists = resolved.exists()
        prior_content = resolved.read_text(encoding="utf-8") if prior_exists else ""
        system_managed = _is_system_managed_metadata_path(op.path)
        decision = classify_file_regen_safety(
            file_path=op.path,
            is_autogenerated=True,
            has_operator_modifications=prior_exists and not system_managed,
            is_production_critical=_is_production_critical_path(op.path),
        )
        lifecycle_decisions.append(decision)
        if prior_exists and bool(decision.get("requires_approval", False)):
            raise RuntimeError(
                f"Lifecycle guardrail blocked update for '{op.path}': explicit approval required"
            )
        resolved.parent.mkdir(parents=True, exist_ok=True)
        prior = prior_content
        next_content = f"{prior}{op.content}"
        resolved.write_text(next_content, encoding="utf-8")
        expected_hash = _sha256(next_content)
        actual_hash = _sha256_bytes(resolved.read_bytes())
        if expected_hash != actual_hash:
            raise RuntimeError(f"Hash verification failed for updated file: {op.path}")
        return {"op": op.op, "path": op.path, "status": "ok", "sha256": actual_hash}

    raise ValueError(f"Unsupported operation: {op.op}")


def apply_build_plan(plan: BuildPlan) -> BuildExecutionResult:
    target = Path(plan.target_repo).resolve()
    target.mkdir(parents=True, exist_ok=True)

    lifecycle_decisions: list[dict[str, object]] = []
    applied = [_apply_operation(target, operation, lifecycle_decisions) for operation in plan.operations]

    # Emit deterministic lifecycle guardrail decisions for regeneration transparency.
    lifecycle_payload = {
        "contract_version": "v1",
        "decision_count": len(lifecycle_decisions),
        "decisions": lifecycle_decisions,
    }
    lifecycle_path = _resolve_scoped_path(target, ".autobuilder/lifecycle_regeneration_decisions.json")
    lifecycle_path.parent.mkdir(parents=True, exist_ok=True)
    lifecycle_content = json.dumps(lifecycle_payload, indent=2, sort_keys=True) + "\n"
    lifecycle_path.write_text(lifecycle_content, encoding="utf-8")
    lifecycle_hash = _sha256_bytes(lifecycle_path.read_bytes())
    applied.append(
        {
            "op": "write_file",
            "path": ".autobuilder/lifecycle_regeneration_decisions.json",
            "status": "ok",
            "sha256": lifecycle_hash,
        }
    )

    output_files, output_hash = _build_output_manifest(applied)
    return BuildExecutionResult(
        target_repo=str(target),
        operations_applied=applied,
        output_hash=output_hash,
        output_files=output_files,
        lifecycle_regeneration_decisions=lifecycle_decisions,
    )
