from __future__ import annotations

import json
from dataclasses import dataclass

from ir.model import AppIR


@dataclass(frozen=True)
class GeneratedTemplate:
    path: str
    content: str


def _json_pretty(payload: dict[str, object]) -> str:
    return f"{json.dumps(payload, indent=2)}\n"


def _frontend_package_json() -> str:
    return _json_pretty(
        {
            "name": "frontend",
            "private": True,
            "version": "0.1.0",
            "scripts": {
                "dev": "next dev -p 3000",
                "build": "next build",
                "start": "next start -p 3000",
                "test:shell": "node tests/shell-check.js",
            },
            "dependencies": {
                "next": "14.2.5",
                "react": "18.3.1",
                "react-dom": "18.3.1",
            },
        }
    )


def _frontend_tsconfig_json() -> str:
    return _json_pretty(
        {
            "compilerOptions": {
                "target": "ES2020",
                "lib": ["dom", "dom.iterable", "esnext"],
                "allowJs": False,
                "skipLibCheck": True,
                "strict": True,
                "noEmit": True,
                "module": "esnext",
                "moduleResolution": "bundler",
                "resolveJsonModule": True,
                "isolatedModules": True,
                "jsx": "preserve",
                "incremental": True,
            },
            "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
            "exclude": ["node_modules"],
        }
    )


def _frontend_status_seed(ir: AppIR) -> str:
    return _json_pretty(
        {
            "appIdentity": ir.app_identity,
            "status": "idle",
            "lastCommand": "",
            "lastResponse": "Ready",
            "surface": "workspace",
        }
    )


def _frontend_shell_page(ir: AppIR) -> str:
    return f'''"use client";

import {{ useState }} from "react";

type ApiResponse = {{
  status: string;
  command: string;
  result: string;
}};

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";

export default function HomePage() {{
  const [command, setCommand] = useState("");
  const [status, setStatus] = useState("idle");
  const [response, setResponse] = useState("Waiting for input");

  async function runCommand() {{
    setStatus("processing");
    setResponse("Contacting backend...");

    try {{
      const res = await fetch(`${{API_BASE}}/api/workspace/execute`, {{
        method: "POST",
        headers: {{ "Content-Type": "application/json" }},
        body: JSON.stringify({{ command }}),
      }});

      if (!res.ok) {{
        throw new Error(`API request failed with status ${{res.status}}`);
      }}

      const payload = (await res.json()) as ApiResponse;
      setStatus(payload.status);
      setResponse(payload.result);
    }} catch (error) {{
      const message = error instanceof Error ? error.message : "Unknown error";
      setStatus("error");
      setResponse(message);
    }}
  }}

  return (
    <main className="shell" data-testid="workspace-shell">
      <header className="shell-header">
        <h1>{ir.app_identity}</h1>
        <p>Commercial starter shell for operator-driven workspace apps.</p>
      </header>

      <section className="command-panel" data-testid="command-surface">
        <label htmlFor="command-input">Command</label>
        <div className="command-row">
          <input
            id="command-input"
            value={{command}}
            onChange={{(event) => setCommand(event.target.value)}}
            placeholder="Type a command for backend execution"
          />
          <button type="button" onClick={{runCommand}}>
            Execute
          </button>
        </div>
      </section>

      <section className="work-surface" data-testid="main-surface">
        <h2>Work Surface</h2>
        <p>
          Primary content area for task output, records, and operator-facing tools.
        </p>
      </section>

      <aside className="status-panel" data-testid="status-panel">
        <h2>Status</h2>
        <p>
          <strong>State:</strong> {{status}}
        </p>
        <p>
          <strong>Response:</strong> {{response}}
        </p>
      </aside>
    </main>
  );
}}
'''


def _frontend_layout() -> str:
    return '''import "./globals.css";
import type { ReactNode } from "react";

export const metadata = {
  title: "Autobuilder Commercial Starter",
  description: "React/Next workspace shell generated by AutobuilderV2",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
'''


def _frontend_css() -> str:
    return ''':root {
  --bg: #f4f3ef;
  --panel: #ffffff;
  --ink: #171412;
  --muted: #5a5049;
  --accent: #0f6b8f;
  --accent-strong: #0a4f69;
  --border: #d7cfc8;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: radial-gradient(circle at 10% 10%, #ffffff 0%, #f4f3ef 45%, #ece8df 100%);
  color: var(--ink);
  font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
}

.shell {
  display: grid;
  gap: 1rem;
  grid-template-columns: 2fr 1fr;
  grid-template-areas:
    "header header"
    "command status"
    "main status";
  min-height: 100vh;
  padding: 1.25rem;
}

.shell-header {
  grid-area: header;
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1rem;
}

.shell-header h1 {
  margin: 0;
  font-size: 1.5rem;
}

.shell-header p {
  color: var(--muted);
  margin-top: 0.5rem;
}

.command-panel,
.work-surface,
.status-panel {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1rem;
}

.command-panel {
  grid-area: command;
}

.work-surface {
  grid-area: main;
}

.status-panel {
  grid-area: status;
}

.command-row {
  display: flex;
  gap: 0.5rem;
  margin-top: 0.5rem;
}

input {
  flex: 1;
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 0.6rem;
  font-size: 0.95rem;
}

button {
  border: 0;
  border-radius: 8px;
  padding: 0.6rem 1rem;
  background: var(--accent);
  color: #ffffff;
  cursor: pointer;
}

button:hover {
  background: var(--accent-strong);
}

@media (max-width: 900px) {
  .shell {
    grid-template-columns: 1fr;
    grid-template-areas:
      "header"
      "command"
      "main"
      "status";
  }
}
'''


def _frontend_shell_check() -> str:
    return '''const fs = require("fs");
const path = require("path");

const shellPath = path.join(__dirname, "..", "app", "page.tsx");
const content = fs.readFileSync(shellPath, "utf-8");

const requiredMarkers = [
  'data-testid="workspace-shell"',
  'data-testid="command-surface"',
  'data-testid="main-surface"',
  'data-testid="status-panel"',
  '/api/workspace/execute',
];

for (const marker of requiredMarkers) {
  if (!content.includes(marker)) {
    throw new Error(`Missing required shell marker: ${marker}`);
  }
}

console.log("frontend shell check passed");
'''


def _backend_app() -> str:
    return '''from __future__ import annotations

from fastapi import FastAPI
from pydantic import BaseModel

from api.config import Settings, get_settings


class CommandRequest(BaseModel):
    command: str


app = FastAPI(title="Autobuilder Commercial Starter API")


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def readiness() -> dict[str, str]:
    settings = get_settings()
    return {"status": "ready", "database_url": settings.database_url}


@app.get("/version")
def version() -> dict[str, str]:
    settings = get_settings()
    return {"version": settings.app_version}


@app.post("/api/workspace/execute")
def execute_workspace_command(payload: CommandRequest) -> dict[str, str]:
    sanitized = payload.command.strip() or "noop"
    return {
        "status": "ok",
        "command": sanitized,
        "result": f"accepted command: {sanitized}",
    }
'''


def _backend_config() -> str:
    return '''from __future__ import annotations

from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_env: str = "local"
    app_version: str = "0.1.0"
    database_url: str = "postgresql://postgres:postgres@db:5432/app"
    cors_origin: str = "http://localhost:3000"

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
'''


def _backend_requirements() -> str:
    return "fastapi==0.115.0\nuvicorn==0.30.6\npydantic-settings==2.5.2\npytest==8.3.3\nhttpx==0.27.2\n"


def _backend_test() -> str:
    return '''from fastapi.testclient import TestClient

from api.main import app


client = TestClient(app)


def test_health_endpoint() -> None:
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_readiness_endpoint() -> None:
    response = client.get("/ready")
    assert response.status_code == 200
    assert response.json()["status"] == "ready"


def test_version_endpoint() -> None:
    response = client.get("/version")
    assert response.status_code == 200
    assert "version" in response.json()


def test_workspace_execute_shape() -> None:
    response = client.post("/api/workspace/execute", json={"command": "refresh dashboard"})
    assert response.status_code == 200
    payload = response.json()
    assert payload["status"] == "ok"
    assert payload["command"] == "refresh dashboard"
    assert "accepted command" in payload["result"]
'''


def _docker_compose() -> str:
    return '''services:
  frontend:
    image: node:20
    working_dir: /workspace/frontend
    command: sh -c "npm install && npm run dev"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./:/workspace
    depends_on:
      - backend

  backend:
    image: python:3.12-slim
    working_dir: /workspace/backend
    command: sh -c "pip install -r requirements.txt && uvicorn api.main:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
      APP_ENV: local
      APP_VERSION: 0.1.0
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "8000:8000"
    volumes:
      - ./:/workspace
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
'''


def _root_readme(ir: AppIR) -> str:
    return f'''# {ir.app_identity}

Commercial starter application generated by AutobuilderV2.

## Included stack

- Frontend: React/Next workspace shell
- Backend: FastAPI API service
- Database assumptions: Postgres environment wiring
- Deployment: Docker Compose for local startup

## Starter structure

- One command input surface in frontend shell
- One main content/work surface
- One status/response panel
- Operator/admin placeholders under docs and api routes

## Local run

1. Start everything:

```bash
docker compose up
```

2. Open frontend at http://localhost:3000
3. API health endpoint: http://localhost:8000/health

## Backend tests

```bash
cd backend
pip install -r requirements.txt
pytest -q
```

## Frontend shell check

```bash
cd frontend
npm install
npm run test:shell
```
'''


def _generated_readme() -> str:
    return '''# Generated Assets

This directory records deterministic metadata about the generated starter app.

- ir.json: normalized internal representation used for generation
- build_plan.json: intended structures and modules
- generation_summary.json: emitted files and validation plan
'''


def _build_validation_plan() -> list[str]:
    return [
        "backend_pytest_endpoints",
        "frontend_shell_structure_check",
        "docker_compose_service_boot",
        "manual_smoke_health_and_ready",
    ]


def generate_first_class_templates(ir: AppIR) -> list[GeneratedTemplate]:
    return [
        GeneratedTemplate(path="README.md", content=_root_readme(ir)),
        GeneratedTemplate(path=".env.example", content=(
            "APP_ENV=local\n"
            "APP_VERSION=0.1.0\n"
            "DATABASE_URL=postgresql://postgres:postgres@db:5432/app\n"
            "CORS_ORIGIN=http://localhost:3000\n"
            "NEXT_PUBLIC_API_BASE_URL=http://localhost:8000\n"
        )),
        GeneratedTemplate(path="docker-compose.yml", content=_docker_compose()),
        GeneratedTemplate(path="frontend/package.json", content=_frontend_package_json()),
        GeneratedTemplate(path="frontend/tsconfig.json", content=_frontend_tsconfig_json()),
        GeneratedTemplate(path="frontend/next-env.d.ts", content='/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n'),
        GeneratedTemplate(path="frontend/next.config.js", content='/** @type {import("next").NextConfig} */\nconst nextConfig = {};\n\nmodule.exports = nextConfig;\n'),
        GeneratedTemplate(path="frontend/app/layout.tsx", content=_frontend_layout()),
        GeneratedTemplate(path="frontend/app/page.tsx", content=_frontend_shell_page(ir)),
        GeneratedTemplate(path="frontend/app/globals.css", content=_frontend_css()),
        GeneratedTemplate(path="frontend/tests/shell-check.js", content=_frontend_shell_check()),
        GeneratedTemplate(path="frontend/public/.gitkeep", content=""),
        GeneratedTemplate(path="frontend/status.seed.json", content=_frontend_status_seed(ir)),
        GeneratedTemplate(path="backend/requirements.txt", content=_backend_requirements()),
        GeneratedTemplate(path="backend/api/__init__.py", content=""),
        GeneratedTemplate(path="backend/api/main.py", content=_backend_app()),
        GeneratedTemplate(path="backend/api/config.py", content=_backend_config()),
        GeneratedTemplate(path="backend/tests/test_endpoints.py", content=_backend_test()),
        GeneratedTemplate(path="backend/.env.example", content=(
            "APP_ENV=local\n"
            "APP_VERSION=0.1.0\n"
            "DATABASE_URL=postgresql://postgres:postgres@db:5432/app\n"
            "CORS_ORIGIN=http://localhost:3000\n"
        )),
        GeneratedTemplate(path="db/schema.sql", content=(
            "CREATE TABLE IF NOT EXISTS users (\n"
            "  id SERIAL PRIMARY KEY,\n"
            "  email TEXT NOT NULL UNIQUE,\n"
            "  role TEXT NOT NULL DEFAULT 'user'\n"
            ");\n"
        )),
        GeneratedTemplate(path="docs/OPERATOR.md", content=(
            "# Operator Notes\n\n"
            "- Add admin routes under backend/api/admin.py\n"
            "- Add privileged workspace actions behind role checks\n"
            "- Keep execution actions auditable\n"
        )),
        GeneratedTemplate(path=".autobuilder/README.md", content=_generated_readme()),
    ]


def first_class_validation_plan() -> list[str]:
    return _build_validation_plan()
